strategy:
  matrix:
    linux:
      imageName: ubuntu-20.04
    mac:
      imageName: macOS-10.15
    windows:
      imageName: windows-2019

pool:
  vmImage: $(imageName)

steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleDebug testDebug'
  displayName: gradlew assembleDebug testDebug
