on: [push, pull_request]
jobs:
  gradle-android-test:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    # TODO(robinlinden): Fix tests failing sporadically in CI.
    - name: Test
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: ./gradlew connectedCheck -x :atox:connectedAndroidTest -x :domain:connectedAndroidTest || { adb logcat -d; exit 1; }

  ktlint:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: ktlint
      run: ./gradlew ktlint

  gradle:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 6
      matrix:
        os:
        - ubuntu-18.04
        - macOS-10.15
        - windows-2019
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build and test
      run: ./gradlew build

  bazel:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    # Failed to create a Robolectric sandbox: Android SDK 29 requires Java 9
    - uses: actions/setup-java@v1
      with:
        java-version: 9
    - name: Set up Android
      run: |
          echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --install "ndk;$NDK_VERSION" | grep -v = || true
          echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/$NDK_VERSION" >> $GITHUB_ENV
      env:
        NDK_VERSION: 21.3.6528147
    - name: Install
      run: wget https://github.com/bazelbuild/bazelisk/releases/download/v1.7.4/bazelisk-linux-amd64 --output-document=bazelisk
    - name: Build
      run: bazelisk build //...
    - name: Test
      run: bazelisk test //...

  buildifier:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: |
          wget https://github.com/bazelbuild/buildtools/releases/download/3.5.0/buildifier
          sudo chmod +x buildifier
    - name: Check
      run: ./buildifier --lint=warn --warnings=all -mode diff WORKSPACE $(find . -type f -iname BUILD.*)

  gradle-from-source:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install tox4j dependencies
      run: sudo apt install yasm
    - name: Disallow fetching tox4j
      run: sed -i '/dl.bintray.com\/toktok\/maven/d' build.gradle.kts
    - name: Fix tox4j dependency versions
      run: |
        sed -i 's/\$oldVersion/\$version/' buildSrc/src/main/kotlin/Dependencies.kt
        sed -i 's/tox4j-c_arm-linux-androideabi/tox4j-c_armv7a-linux-androideabi/' buildSrc/src/main/kotlin/Dependencies.kt
    - name: Build tox4j
      run: |
        ./scripts/build-host -j$(nproc || sysctl -n hw.ncpu)
        ./scripts/build-aarch64-linux-android -j$(nproc || sysctl -n hw.ncpu) release
        ./scripts/build-arm-linux-androideabi -j$(nproc || sysctl -n hw.ncpu) release
        ./scripts/build-i686-linux-android -j$(nproc || sysctl -n hw.ncpu) release
        ./scripts/build-x86_64-linux-android -j$(nproc || sysctl -n hw.ncpu) release
    - name: Build aTox
      run: ./gradlew build
